version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:80"
    # No volumes needed since Dockerfile copies files

    # Remove volume reference if you are copying all files directly
    # volumes:
    #   - ./web:/usr/share/nginx/html

